# Generated by Django 3.1.4 on 2020-12-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courses',
            fields=[
                ('coursename', models.CharField(max_length=40)),
                ('courseid', models.IntegerField(default=6, primary_key=True, serialize=False)),
                ('coursefee', models.IntegerField(default=6)),
                ('courseduration', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.IntegerField(default=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('contact', models.IntegerField(default=10)),
                ('gender', models.CharField(max_length=5)),
                ('username', models.CharField(max_length=40)),
                ('password', models.IntegerField(default=20)),
                ('email', models.EmailField(max_length=254)),
                ('course', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('contect', models.IntegerField(default=10, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=6)),
                ('username', models.CharField(max_length=40)),
                ('password', models.IntegerField(default=10)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
