# Generated by Django 3.1.4 on 2020-12-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=15),
        ),
    ]
