# Generated by Django 3.1.4 on 2020-12-23 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationapp', '0002_auto_20201223_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAddDetails',
            fields=[
                ('name', models.CharField(max_length=40)),
                ('contect', models.IntegerField(default=10, primary_key=True, serialize=False)),
                ('qualification', models.CharField(max_length=40)),
                ('course', models.CharField(max_length=40)),
                ('timmeing', models.TimeField()),
            ],
        ),
    ]
