# Generated by Django 3.1.4 on 2020-12-24 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationapp', '0004_auto_20201223_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='id',
            field=models.AutoField(default=5, primary_key=True, serialize=False),
        ),
    ]
